// <auto-generated />
using GymFit.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymFit.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200808182831_populatedata")]
    partial class populatedata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GymFit.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Image = "/Images/Clothing.jpg",
                            Name = "Clothings"
                        },
                        new
                        {
                            CategoryId = 2,
                            Image = "/Images/Footwear.jpg",
                            Name = "FootWears"
                        },
                        new
                        {
                            CategoryId = 3,
                            Image = "/Images/equipments.jpg",
                            Name = "Equipments"
                        },
                        new
                        {
                            CategoryId = 4,
                            Image = "/Images/Suppliment.jpg",
                            Name = "Suppliments"
                        });
                });

            modelBuilder.Entity("GymFit.Models.CategoryDetail", b =>
                {
                    b.Property<int>("CategoryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryDetailId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("CategoryDetails");

                    b.HasData(
                        new
                        {
                            CategoryDetailId = 1,
                            CategoryId = 1,
                            SubCategoryId = 1
                        },
                        new
                        {
                            CategoryDetailId = 2,
                            CategoryId = 1,
                            SubCategoryId = 2
                        },
                        new
                        {
                            CategoryDetailId = 3,
                            CategoryId = 2,
                            SubCategoryId = 1
                        },
                        new
                        {
                            CategoryDetailId = 4,
                            CategoryId = 2,
                            SubCategoryId = 2
                        },
                        new
                        {
                            CategoryDetailId = 5,
                            CategoryId = 3,
                            SubCategoryId = 3
                        },
                        new
                        {
                            CategoryDetailId = 6,
                            CategoryId = 3,
                            SubCategoryId = 4
                        });
                });

            modelBuilder.Entity("GymFit.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            ProductDetailId = 1,
                            Url = "/productimages/dumbbell1.png"
                        },
                        new
                        {
                            ImageId = 2,
                            ProductDetailId = 2,
                            Url = "/productimages/decline-benchpress.png"
                        },
                        new
                        {
                            ImageId = 3,
                            ProductDetailId = 3,
                            Url = "/productimages/whey.jpg"
                        },
                        new
                        {
                            ImageId = 4,
                            ProductDetailId = 4,
                            Url = "/productimages/bigwhey.png"
                        });
                });

            modelBuilder.Entity("GymFit.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFrontPageProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Safety")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sale")
                        .HasColumnType("bit");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsFrontPageProduct = true,
                            Name = "Dumb bells",
                            ProductDetailId = 0,
                            Sale = false
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "WHEY",
                            Description = " Optimum Nutrition’s Gold Standard Whey has been the world’s no 1 choice in whey protein powder for over 20 years. Having constantly refined their formula, the current incarnation of ON’s Gold Standard Whey is the most efficient and fast-absorbing yet, using whey protein isolates as the key ingredient, which help your muscles build and repair. Low quantities of sugar and fat keep things on the healthy side. Gold Standard Whey’s instantised ready-to-mix formula means you can enjoy it any time of day, whether shaken up in a bottle or as an addition to yourfavourite meals and drinks. Available in 1, 2, 5, 7 and 10-pound options. NOTE:Not every product has a hologram on the neck seal .",
                            Ingredient = "Protein Blend (Whey Protein Isolates [contains Emulsifier: Soy Lecithin], Whey Protein Concentrate, Whey Peptides), Fat-Reduced Cocoa Powder, Flavorings, Sweeteners (Acesulfame Potassium, Sucralose), Enzyme Complex (Amylase, Protease, Cellulase, Beta-D-Galactosidase, Lipase)",
                            IsFrontPageProduct = false,
                            Name = "Whey Protien 100%",
                            ProductDetailId = 0,
                            Safety = "May contain- Gluten, Egg, Nuts and Peanuts.",
                            Sale = false
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "WHEY",
                            Description = " Optimum Nutrition’s Gold Standard Whey has been the world’s no 1 choice in whey protein powder for over 20 years. Having constantly refined their formula, the current incarnation of ON’s Gold Standard Whey is the most efficient and fast-absorbing yet, using whey protein isolates as the key ingredient, which help your muscles build and repair. Low quantities of sugar and fat keep things on the healthy side. Gold Standard Whey’s instantised ready-to-mix formula means you can enjoy it any time of day, whether shaken up in a bottle or as an addition to yourfavourite meals and drinks. Available in 1, 2, 5, 7 and 10-pound options. NOTE:Not every product has a hologram on the neck seal .",
                            Ingredient = "Protein Blend (Whey Protein Isolates [contains Emulsifier: Soy Lecithin], Whey Protein Concentrate, Whey Peptides), Fat-Reduced Cocoa Powder, Flavorings, Sweeteners (Acesulfame Potassium, Sucralose), Enzyme Complex (Amylase, Protease, Cellulase, Beta-D-Galactosidase, Lipase)",
                            IsFrontPageProduct = false,
                            Name = "Whey Protien 50%",
                            ProductDetailId = 0,
                            Safety = "May contain- Gluten, Egg, Nuts and Peanuts.",
                            Sale = false
                        },
                        new
                        {
                            ProductId = 4,
                            IsFrontPageProduct = true,
                            Name = "Decline BenchPress",
                            ProductDetailId = 0,
                            Sale = false
                        });
                });

            modelBuilder.Entity("GymFit.Models.ProductDetail", b =>
                {
                    b.Property<int>("ProductDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Flavour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PreviousPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("StockAmount")
                        .HasColumnType("int");

                    b.Property<int>("Weights")
                        .HasColumnType("int");

                    b.HasKey("ProductDetailId");

                    b.HasIndex("CategoryDetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            ProductDetailId = 1,
                            CategoryDetailId = 3,
                            PreviousPrice = 240m,
                            Price = 120m,
                            ProductId = 1,
                            Size = 0,
                            StockAmount = 2000,
                            Weights = 0
                        },
                        new
                        {
                            ProductDetailId = 2,
                            CategoryDetailId = 4,
                            PreviousPrice = 84m,
                            Price = 40m,
                            ProductId = 3,
                            Size = 0,
                            StockAmount = 2000,
                            Weights = 0
                        },
                        new
                        {
                            ProductDetailId = 3,
                            CategoryDetailId = 4,
                            PreviousPrice = 324m,
                            Price = 20m,
                            ProductId = 3,
                            Size = 0,
                            StockAmount = 2000,
                            Weights = 0
                        },
                        new
                        {
                            ProductDetailId = 4,
                            CategoryDetailId = 4,
                            PreviousPrice = 84m,
                            Price = 40m,
                            ProductId = 4,
                            Size = 0,
                            StockAmount = 2000,
                            Weights = 0
                        },
                        new
                        {
                            ProductDetailId = 5,
                            CategoryDetailId = 4,
                            PreviousPrice = 324m,
                            Price = 20m,
                            ProductId = 4,
                            Size = 0,
                            StockAmount = 2000,
                            Weights = 0
                        },
                        new
                        {
                            ProductDetailId = 6,
                            CategoryDetailId = 3,
                            PreviousPrice = 240m,
                            Price = 120m,
                            ProductId = 2,
                            Size = 0,
                            StockAmount = 2000,
                            Weights = 0
                        });
                });

            modelBuilder.Entity("GymFit.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            Name = "Men"
                        },
                        new
                        {
                            SubCategoryId = 2,
                            Name = "Women"
                        },
                        new
                        {
                            SubCategoryId = 3,
                            Name = "Weights/Dumbbells"
                        },
                        new
                        {
                            SubCategoryId = 4,
                            Name = "Fitness Equipment"
                        });
                });

            modelBuilder.Entity("GymFit.Models.CategoryDetail", b =>
                {
                    b.HasOne("GymFit.Models.Category", null)
                        .WithMany("CategoryDetails")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFit.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymFit.Models.Image", b =>
                {
                    b.HasOne("GymFit.Models.ProductDetail", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymFit.Models.ProductDetail", b =>
                {
                    b.HasOne("GymFit.Models.CategoryDetail", "CategoryDetail")
                        .WithMany()
                        .HasForeignKey("CategoryDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFit.Models.Product", "Product")
                        .WithMany("ProductDetail")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
